---
apiVersion: v1
kind: Namespace
metadata:
  name: dev-env
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
  namespace: dev-env
data:
  DATABASE_URL: "postgres://user:password@hostname:5432/dbname"
  REDIS_HOST: "redis-server"
  REDIS_PORT: "6379"
  APP_MODE: "production"
  NAME: "shammu"
  PLACE: "hyd"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: dev-env
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dm
  template:
    metadata:
      labels:
        app: dm
    spec:
      containers:
      - name: dm
        image: shammu101/dm # Replace with your actual image if needed
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: my-config
spec:
  containers:
    - name: dm
      image: shammu101/dm
      env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: DATABASE_URL
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: REDIS_PORT
        - name: APP_MODE
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: APP_MODE

---
apiVersion: v1
kind: Service
metadata:
  name: httpd
  namespace: dev-env
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: dm
