---
apiVersion: v1
kind: Namespace
metadata:
  name: dev-env
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
  namespace: dev-env
data:
  DATABASE_URL: "postgres://user:password@hostname:5432/dbname"
  REDIS_HOST: "redis-server"
  REDIS_PORT: "6379"
  APP_MODE: "production"
  NAME: "shammu"
  PLACE: "hyd"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: dev-env
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: nginx:latest # Replace with your actual image if needed
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: my-config
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: dev-env
spec:
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
